spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb?sslmode=disable
    username: marus
    password: marus
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  data:
    redis:
      host: redis
      port: 6379
      repositories:
        enabled: false

server:
  port: 8080

jwt:
  sign:
    private-key: keys/rsa-sign-priv.pem
    public-key:  keys/rsa-sign-pub.pem
  enc:
    private-key: keys/rsa-enc-priv.pem
    public-key:  keys/rsa-enc-pub.pem
  access-exp: 900000
  refresh-exp: 604800000